name: Plugin_Development
version: '1.0-SNAPSHOT'
main: main.plugin_Develompent.Plugin_Development  # Corrected package name and class name
api-version: '1.21'

commands:
  turtlehatche:
    description: Get a Turtle Hatcher
    usage: /turtlehatche
  thelauncher:
    description: Get The Launcher
    usage: /thelauncher
  giveglacialscepter:
    description: Gives the player the Glacial Scepter item.
    usage: /giveglacialscepter
    permission: glacialscepter.give
    permission-message: "You don't have permission to use this command."
  givecrimsongauntlet:
    description: Gives the player the Crimson Gauntlet item.
    usage: /givecrimsongauntlet
    permission: crimsongauntlet.give
    permission-message: "You don't have permission to use this command."
  challenges:
    description: Start/Stop challenges like Block Break and Random Block.
    usage: /challenges <start/stop/randomstart/randomstop>